tokens: add abigen go gen for ERC20 interface
storj/storjscan pull request #31
Opened 2022-03-15 14:05 UTC by rikysya

2022-03-15 18:59 UTC, jenlij submitted a review, later dismissed

2022-03-15 20:44 UTC, dlamarmorgan requested changes

2022-03-15 20:44 UTC, dlamarmorgan commented on tokens/gen.go
> +//go:generate abigen --bin=../contracts/build/ERC20.bin --abi=../contracts/build/ERC20.abi --type=ERC20 --pkg=erc20 --out=erc20/erc20.go
Whenever I try a go generate, I get the error
Fatal: Failed to read input ABI: open ../../contracts/build/TestToken.abi: The system cannot find the path specified.
What am I doing wrong? I've tried running go install and go build but I do not see the /contracts/build folder showing up anywhere.

2022-03-16 18:25 UTC, dlamarmorgan approved these changes

2022-03-16 20:41 UTC, jenlij approved these changes

2022-03-16 20:43 UTC, merged